package com.bcnc_group_test.entities;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum CurrencyCode {
    AED("United Arab Emirates Dirham", "AED", "د.إ"),
    AFN("Afghanistan Afghani", "AFN", "؋"),
    ALL("Albania Lek", "ALL", "L"),
    AMD("Armenia Dram", "AMD", "֏"),
    ANG("Netherlands Antilles Guilder", "ANG", "ƒ"),
    AOA("Angola Kwanza", "AOA", "Kz"),
    ARS("Argentina Peso", "ARS", "$"),
    AUD("Australia Dollar", "AUD", "$"),
    AWG("Aruba Guilder", "AWG", "ƒ"),
    AZN("Azerbaijan New Manat", "AZN", "₼"),
    BAM("Bosnia and Herzegovina Convertible Marka", "BAM", "KM"),
    BBD("Barbados Dollar", "BBD", "$"),
    BDT("Bangladesh Taka", "BDT", "৳"),
    BGN("Bulgaria Lev", "BGN", "лв"),
    BHD("Bahrain Dinar", "BHD", ".د.ب"),
    BIF("Burundi Franc", "BIF", "FBu"),
    BMD("Bermuda Dollar", "BMD", "$"),
    BND("Brunei Darussalam Dollar", "BND", "$"),
    BOB("Bolivia Bolíviano", "BOB", "Bs."),
    BRL("Brazil Real", "BRL", "R$"),
    BSD("Bahamas Dollar", "BSD", "$"),
    BTN("Bhutan Ngultrum", "BTN", "Nu."),
    BWP("Botswana Pula", "BWP", "P"),
    BYR("Belarus Ruble", "BYR", "Br"),
    BZD("Belize Dollar", "BZD", "$"),
    CAD("Canada Dollar", "CAD", "$"),
    CDF("Congo/Kinshasa Franc", "CDF", "FC"),
    CHF("Switzerland Franc", "CHF", "Fr."),
    CLP("Chile Peso", "CLP", "$"),
    CNY("China Yuan Renminbi", "CNY", "¥"),
    COP("Colombia Peso", "COP", "$"),
    CRC("Costa Rica Colon", "CRC", "₡"),
    CUC("Cuba Convertible Peso", "CUC", "$"),
    CUP("Cuba Peso", "CUP", "$"),
    CVE("Cape Verde Escudo", "CVE", "$"),
    CZK("Czech Republic Koruna", "CZK", "Kč"),
    DJF("Djibouti Franc", "DJF", "Fdj"),
    DKK("Denmark Krone", "DKK", "kr"),
    DOP("Dominican Republic Peso", "DOP", "RD$"),
    DZD("Algeria Dinar", "DZD", "دج"),
    EGP("Egypt Pound", "EGP", "£"),
    ERN("Eritrea Nakfa", "ERN", "Nfk"),
    ETB("Ethiopia Birr", "ETB", "Br"),
    EUR("Euro Member Countries", "EUR", "€"),
    FJD("Fiji Dollar", "FJD", "$"),
    FKP("Falkland Islands (Malvinas) Pound", "FKP", "£"),
    GBP("United Kingdom Pound", "GBP", "£"),
    GEL("Georgia Lari", "GEL", "₾"),
    GGP("Guernsey Pound", "GGP", "£"),
    GHS("Ghana Cedi", "GHS", "₵"),
    GIP("Gibraltar Pound", "GIP", "£"),
    GMD("Gambia Dalasi", "GMD", "D"),
    GNF("Guinea Franc", "GNF", "FG"),
    GTQ("Guatemala Quetzal", "GTQ", "Q"),
    GYD("Guyana Dollar", "GYD", "$"),
    HKD("Hong Kong Dollar", "HKD", "$"),
    HNL("Honduras Lempira", "HNL", "L"),
    HRK("Croatia Kuna", "HRK", "kn"),
    HTG("Haiti Gourde", "HTG", "G"),
    HUF("Hungary Forint", "HUF", "Ft"),
    IDR("Indonesia Rupiah", "IDR", "Rp"),
    ILS("Israel Shekel", "ILS", "₪"),
    IMP("Isle of Man Pound", "IMP", "£"),
    INR("India Rupee", "INR", "₹"),
    IQD("Iraq Dinar", "IQD", "ع.د"),
    IRR("Iran Rial", "IRR", "﷼"),
    ISK("Iceland Krona", "ISK", "kr"),
    JEP("Jersey Pound", "JEP", "£"),
    JMD("Jamaica Dollar", "JMD", "$"),
    JOD("Jordan Dinar", "JOD", "د.ا"),
    JPY("Japan Yen", "JPY", "¥"),
    KES("Kenya Shilling", "KES", "KSh"),
    KGS("Kyrgyzstan Som", "KGS", "лв"),
    KHR("Cambodia Riel", "KHR", "៛"),
    KMF("Comoros Franc", "KMF", "CF"),
    KPW("Korea (North) Won", "KPW", "₩"),
    KRW("Korea (South) Won", "KRW", "₩"),
    KWD("Kuwait Dinar", "KWD", "د.ك"),
    KYD("Cayman Islands Dollar", "KYD", "$"),
    KZT("Kazakhstan Tenge", "KZT", "₸"),
    LAK("Laos Kip", "LAK", "₭"),
    LBP("Lebanon Pound", "LBP", "ل.ل"),
    LKR("Sri Lanka Rupee", "LKR", "රු"),
    LRD("Liberia Dollar", "LRD", "$"),
    LSL("Lesotho Loti", "LSL", "L"),
    LYD("Libya Dinar", "LYD", "ل.د"),
    MAD("Morocco Dirham", "MAD", "د.م."),
    MDL("Moldova Leu", "MDL", "L"),
    MGA("Madagascar Ariary", "MGA", "Ar"),
    MKD("Macedonia Denar", "MKD", "ден"),
    MMK("Myanmar (Burma) Kyat", "MMK", "K"),
    MNT("Mongolia Tughrik", "MNT", "₮"),
    MOP("Macau Pataca", "MOP", "MOP$"),
    MRO("Mauritania Ouguiya", "MRO", "UM"),
    MUR("Mauritius Rupee", "MUR", "₨"),
    MVR("Maldives (Maldive Islands) Rufiyaa", "MVR", ".ރ"),
    MWK("Malawi Kwacha", "MWK", "MK"),
    MXN("Mexico Peso", "MXN", "$"),
    MYR("Malaysia Ringgit", "MYR", "RM"),
    MZN("Mozambique Metical", "MZN", "MT"),
    NAD("Namibia Dollar", "NAD", "$"),
    NGN("Nigeria Naira", "NGN", "₦"),
    NIO("Nicaragua Cordoba", "NIO", "C$"),
    NOK("Norway Krone", "NOK", "kr"),
    NPR("Nepal Rupee", "NPR", "₨"),
    NZD("New Zealand Dollar", "NZD", "$"),
    OMR("Oman Rial", "OMR", "ر.ع."),
    PAB("Panama Balboa", "PAB", "B/."),
    PEN("Peru Sol", "PEN", "S/."),
    PGK("Papua New Guinea Kina", "PGK", "K"),
    PHP("Philippines Peso", "PHP", "₱"),
    PKR("Pakistan Rupee", "PKR", "₨"),
    PLN("Poland Zloty", "PLN", "zł"),
    PYG("Paraguay Guarani", "PYG", "₲"),
    QAR("Qatar Riyal", "QAR", "ر.ق"),
    RON("Romania New Leu", "RON", "lei"),
    RSD("Serbia Dinar", "RSD", "дин"),
    RUB("Russia Ruble", "RUB", "₽"),
    RWF("Rwanda Franc", "RWF", "FRw"),
    SAR("Saudi Arabia Riyal", "SAR", "ر.س"),
    SBD("Solomon Islands Dollar", "SBD", "$"),
    SCR("Seychelles Rupee", "SCR", "₨"),
    SDG("Sudan Pound", "SDG", "ج.س."),
    SEK("Sweden Krona", "SEK", "kr"),
    SGD("Singapore Dollar", "SGD", "$"),
    SHP("Saint Helena Pound", "SHP", "£"),
    SLL("Sierra Leone Leone", "SLL", "Le"),
    SOS("Somalia Shilling", "SOS", "Sh"),
    SPL("Seborga Luigino", "SPL", "₤"),
    SRD("Suriname Dollar", "SRD", "$"),
    STD("São Tomé and Príncipe Dobra", "STD", "Db"),
    SVC("El Salvador Colon", "SVC", "$"),
    SYP("Syria Pound", "SYP", "£"),
    SZL("Swaziland Lilangeni", "SZL", "E"),
    THB("Thailand Baht", "THB", "฿"),
    TJS("Tajikistan Somoni", "TJS", "SM"),
    TMT("Turkmenistan Manat", "TMT", "T"),
    TND("Tunisia Dinar", "TND", "د.ت"),
    TOP("Tonga Pa'anga", "TOP", "T$"),
    TRY("Turkey Lira", "TRY", "₺"),
    TTD("Trinidad and Tobago Dollar", "TTD", "$"),
    TVD("Tuvalu Dollar", "TVD", "$"),
    TWD("Taiwan New Dollar", "TWD", "NT$"),
    TZS("Tanzania Shilling", "TZS", "Sh"),
    UAH("Ukraine Hryvnia", "UAH", "₴"),
    UGX("Uganda Shilling", "UGX", "Sh"),
    USD("United States Dollar", "USD", "$"),
    UYU("Uruguay Peso", "UYU", "$U"),
    UZS("Uzbekistan Som", "UZS", "soʻm"),
    VEF("Venezuela Bolivar", "VEF", "Bs"),
    VND("Viet Nam Dong", "VND", "₫"),
    VUV("Vanuatu Vatu", "VUV", "VT"),
    WST("Samoa Tala", "WST", "T"),
    XAF("Communauté Financière Africaine (BEAC) CFA Franc BEAC", "XAF", "FCFA"),
    XCD("East Caribbean Dollar", "XCD", "$"),
    XDR("International Monetary Fund (IMF) Special Drawing Rights", "XDR", "SDR"),
    XOF("Communauté Financière Africaine (BCEAO) Franc", "XOF", "CFA"),
    XPF("Comptoirs Français du Pacifique (CFP) Franc", "XPF", "₣"),
    YER("Yemen Rial", "YER", "﷼"),
    ZAR("South Africa Rand", "ZAR", "R"),
    ZMW("Zambia Kwacha", "ZMW", "ZK"),
    ZWD("Zimbabwe Dollar", "ZWD", "Z$");

    private final String description;
    private final String isoCode;
    private final String symbol;

}
